version: '3.9'

services:
  skill-wallet-api:
    container_name: skill-wallet-api
    image: node:16
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - ENVIRONMENT_IP=localhost
      - SERVER_PORT=4005
      - NODE_ENV=development
    ports:
      - "4005:4005"
    command: /bin/bash -c 'yarn; yarn start;'
    networks:
      - skill-wallet
    deploy:
      restart_policy:
        condition: on-failure


  skillwallet-db:
    container_name: skillwallet-db
    image: mongo
    volumes:
      - ./data-dev:/data/db
    ports:
      - "27017:27017"
    networks:
      - skill-wallet

networks:
  skill-wallet: